### ISSUE TITLE
Change Rcpp::List  to std::vector<float>

### ISSUE THREAD

**Issue by mpadge** [ropensci/parzer#42]
In `split_decimal_degree`

**Comment by AlbanSagouis** [comment]
In the middle of `split_decimal_degree` there is a call to `Rcpp::toString(x)` that takes `float& x `and turns it into `const std::string& x_str`.
How would you do that without calling Rcpp?

The conversion is done to unable a call to `is_negative()` that takes only strings. That seems overkill and a purely numeric cpp solution seems a better solution.
