### ISSUE TITLE
Remove dependency on randgeo?

### ISSUE THREAD

**Issue by maelle** [ropensci/parzer#48]
:wave: @AlbanSagouis! randgeo has been archived on GitHub (not on CRAN yet), as it's no longer maintained. Could it be removed from parzer? Do you need help with that (a PR for instance)?

**Comment by mpadge** [comment]
@maelle It's only used in on example, so can easily be removed. Thanks!
@AlbanSagouis The code is here:
https://github.com/ropensci/parzer/blob/44e2ef90884f86521d57a3f245863943e92e175f/R/parse_hemisphere.R#L31-L32

**Comment by maelle** [comment]
@mpadge thank you!!
@AlbanSagouis could you please tell me when you plan the next CRAN release of parzer? And tell me what that release is on CRAN?

**Comment by AlbanSagouis** [comment]
Hi Maëlle,
I’ll work on `parzer` in April and together with @mpadge, we will remove the dependency on `rcpp` and use `cpp11` instead. So the next CRAN release should be in spring or summer, it will be a major one codewise and hopefully a major performance improvement.
No new feature planned though.

**Comment by maelle** [comment]
thank you!
